import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {
	Button,
	Container,
	Navbar,
	Text,
	Grid,
	Col,
	Link,
	Dropdown,
} from '@nextui-org/react'
import { icons } from '../public/Icon.js'
import InfoCard from '../components/InfoCard'

export default function Home() {
	const collapseItems = [
		'Discover',
		'Create',
		'Build',
		'Login',
		'Sign Up',
		'Features',
	]
	return (
		<>
			<Head>
				<title>NextUI Landing Page</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Container>
				{/* Navbar */}
				<Navbar isBordered variant={'static'}>
					<Navbar.Brand>
						<Navbar.Toggle aria-label='toggle navigation' />
						<Text b color='inherit'>
							🔴 Modern UI Labs
						</Text>
					</Navbar.Brand>
					<Navbar.Content
						hideIn='sm'
						enableCursorHighlight
						variant='highlight'>
						<Dropdown isBordered>
							<Navbar.Item>
								<Dropdown.Button
									auto
									light
									css={{
										px: 0,
										dflex: 'center',
										svg: { pe: 'none' },
									}}
									iconRight={icons.chevron}
									ripple={false}>
									Features
								</Dropdown.Button>
							</Navbar.Item>
							<Dropdown.Menu
								aria-label='ACME features'
								css={{
									$$dropdownMenuWidth: '340px',
									$$dropdownItemHeight: '70px',
									'& .nextui-dropdown-item': {
										py: '$4',
										// dropdown item left icon
										svg: {
											color: '$secondary',
											mr: '$4',
										},
										// dropdown item title
										'& .nextui-dropdown-item-content': {
											w: '100%',
											fontWeight: '$semibold',
										},
									},
								}}>
								<Dropdown.Item
									key='autoscaling'
									showFullDescription
									description='ACME scales apps to meet user demand, automagically, based on load.'
									icon={icons.scale}>
									Autoscaling
								</Dropdown.Item>
								<Dropdown.Item
									key='usage_metrics'
									showFullDescription
									description='Real-time metrics to debug issues. Slow query added? We’ll show you exactly where.'
									icon={icons.activity}>
									Usage Metrics
								</Dropdown.Item>
								<Dropdown.Item
									key='production_ready'
									showFullDescription
									description='ACME runs on ACME, join us and others serving requests at web scale.'
									icon={icons.flash}>
									Production Ready
								</Dropdown.Item>
								<Dropdown.Item
									key='99_uptime'
									showFullDescription
									description='Applications stay on the grid with high availability and high uptime guarantees.'
									icon={icons.server}>
									+99% Uptime
								</Dropdown.Item>
								<Dropdown.Item
									key='supreme_support'
									showFullDescription
									description='Overcome any challenge with a supporting team ready to respond.'
									icon={icons.user}>
									+Supreme Support
								</Dropdown.Item>
							</Dropdown.Menu>
						</Dropdown>
						<Navbar.Link href='#'>Discover</Navbar.Link>
						<Navbar.Link href='#'>Create</Navbar.Link>
						<Navbar.Link href='#'>Build</Navbar.Link>
					</Navbar.Content>
					<Navbar.Content
						hideIn='xs'
						enableCursorHighlight
						variant='highlight'>
						<Navbar.Link href='#'>Login</Navbar.Link>
						<Navbar.Item>
							<Button shadow light auto href='#'>
								Sign in
							</Button>
						</Navbar.Item>
					</Navbar.Content>

					<Navbar.Collapse>
						{collapseItems.map((item) => (
							<Navbar.CollapseItem key={item}>
								<Link
									color='secondary'
									css={{
										minWidth: '100%',
									}}
									href='#'>
									{item}
								</Link>
							</Navbar.CollapseItem>
						))}
					</Navbar.Collapse>
				</Navbar>
				{/* Jumbotron */}
				<Grid.Container
					justify='center'
					css={{
						height: '500px',
						backgroundImage:
							'url(https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1213&q=80)',
					}}>
					<Grid xs={12} sm={6} alignItems='center'>
						<Col css={{ width: '100%' }}>
							<Text
								weight={'thin'}
								size={60}
								css={{ textAlign: 'center' }}>
								Modern UI Labs{' '}
							</Text>
							<Text
								weight={'thin'}
								size={40}
								css={{ textAlign: 'center' }}>
								NextUI{' '}
							</Text>
							<Button
								size='sm'
								shadow
								color='gradient'
								css={{ width: '100%', marginTop: '10px' }}>
								Start me Up
							</Button>
						</Col>
					</Grid>
				</Grid.Container>

				{/* 3 display cards */}
				<Grid.Container gap={2}>
					<Grid xs={12} sm={4}>
						<InfoCard
							label='destination'
							title='Mars'
							bookings='1001'
							imageURL='https://images.unsplash.com/photo-1523597020744-b68b1edd3e1c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1374&q=80'
						/>
					</Grid>
					<Grid xs={12} sm={4}>
						<InfoCard
							label='destination'
							title='Pluto'
							bookings='1501'
							imageURL='https://images.unsplash.com/photo-1614314107768-6018061b5b72?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1374&q=80'
						/>
					</Grid>
					<Grid xs={12} sm={4}>
						<InfoCard
							label='destination'
							title='Neptune'
							bookings='2500'
							imageURL='https://images.unsplash.com/photo-1614313913007-2b4ae8ce32d6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1374&q=80'
						/>
					</Grid>
				</Grid.Container>
			</Container>
		</>
	)
}
